apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "password"
  JWT_SECRET: "9a4f2c8d3b7a1e5f8g6h4j2k0l9m8n7o6p5q4r3s2t1u0v9w8x7y6z5a4b3c2d1e"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
