server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: chatbot-service
  messages:
    encoding: UTF-8

logique-metier:
  url: ${LOGIQUE_METIER_URL:http://localhost:8083}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
